name: Gitaction for python3
on: [push, pull_request]

jobs:
 lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
     - name: Pyflakes Syntax Check
       uses: lgeiger/pyflakes-action@v1.0.1

